version: "3.8"

services:
  backend:
    build: .
    image: backend_learning_image   # ✅ add this line
    container_name: backend_learning
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    networks:
      - backend_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  mongo_data:
