version: "3.8"

services:
  backend:
    build: .
    image: backend_learning_image
    container_name: backend_learning
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - REDIS_URL=redis://redis:6379
    networks:
      - backend_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  mongo_data:
